name: marvel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.2
  dio: ^4.0.6
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
